### PR TITLE
Updated issue template to use two blanks for a newline

### PR DESCRIPTION
**Pull request by julkue**
Let's see what happens when merging this PR.

### CODE REVIEW

**Comment by staceb** [comment]
Looks good on your side?

**Comment by julkue** [comment]
Can't test this in this fork, as issues are disabled. However, I've created a new public repo (don't know if you can access private ones?) with this template:
https://github.com/julmot/test-staceb
Result in the viewer:
great
Result when creating a new issue:
not-great
Can't reproduce the correct behaviour with two blanks, sorry :octocat: 
If you can, what browser and version are you using?

**Comment by julkue** [comment]
@staceb I will make the repository private and only give you access rights. Also I will delete it at the end of the week.

The reason is that I don't want to have trash repos in my account.

**Comment by staceb** [comment]
@julmot strange, I see the wrong behaviour now too.... 
I will create an issue internally and keep you updated! 
Just so I have all the details, can you let me know what browser you are using?

**Comment by julkue** [comment]
I am using the latest Firefox Developer edition (46.0a2). However, it seems to be not a browser specific problem.

Let me know if you need to add further collaborators.

**Pull request merged**
